// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN946JFnuhMMxCummngDS1IYB0UiZMQOo',
    appId: '1:497642805847:android:d315b07c2f6a5f554c6112',
    messagingSenderId: '497642805847',
    projectId: 'taxi-ruta-64097',
    storageBucket: 'taxi-ruta-64097.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC99t42RhdVA4zkA2wxkvCsDzCzakiT9-M',
    appId: '1:497642805847:ios:5699b72b323981fe4c6112',
    messagingSenderId: '497642805847',
    projectId: 'taxi-ruta-64097',
    storageBucket: 'taxi-ruta-64097.firebasestorage.app',
    androidClientId: '497642805847-72gff54l0ffhnhfcd77ruhq6ltrc7pk3.apps.googleusercontent.com',
    iosClientId: '497642805847-aidsu6mtmaihittce00jtrb977up6bqn.apps.googleusercontent.com',
    iosBundleId: 'com.taxiruta.taxiruta',
  );
}
